version: "3"
services:
  zyspotify:
    image: kaitallaoua/zyspotify
    volumes:
      - ./config:/root/config
      - ./Music:/root/Music
    environment:

      # These should be removed after the first run. since credentials cached in db
      - USERNAME=example@gmail.com
      - PASSWORD=hunter2